[package]
name = "facet-json"
version = "0.1.6"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "JSON serialization and deserialization support for Facet traits"
keywords = ["facet", "json", "serialization", "deserialization"]
categories = ["encoding", "development-tools"]

[dependencies]
facet-json-read = { version = "0.1.5", path = "../facet-json-read", optional = true }
facet-json-write = { version = "0.1.5", path = "../facet-json-write", optional = true }

[features]
default = ["read", "write"]
read = ["dep:facet-json-read"]
write = ["dep:facet-json-write"]
