[package]
name = "facet-json"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "JSON serialization and deserialization support for Facet traits"
keywords = ["facet", "json", "serialization", "deserialization"]
categories = ["encoding", "development-tools"]

[dependencies]
facet-core = { version = "0.5.2", path = "../facet-core" }
facet-reflect = { version = "0.6.1", path = "../facet-reflect" }
log = "0.4.27"

[dev-dependencies]
facet = { path = "../facet" }
facet-testhelpers = { version = "0.1.1", path = "../facet-testhelpers" }
