[workspace]
members = [
    "facet",
    "facet-args",
    "facet-codegen",
    "facet-core",
    "facet-derive",
    "facet-json",
    "facet-json-read",
    "facet-json-write",
    "facet-msgpack",
    "facet-peek",
    "facet-poke",
    "facet-pretty",
    "facet-samplelibc",
    "facet-toml",
    "facet-urlencoded",
    "facet-yaml",
]
resolver = "3"

[workspace.package]
version = "0.1.9"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.86.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/facet-rs/facet"

[workspace.dependencies]
facet = { version = "0.1.16", path = "facet" }
facet-derive = { version = "0.1.15", path = "facet-derive" }
facet-peek = { version = "0.2.12", path = "facet-peek" }
facet-poke = { version = "0.5.1", path = "facet-poke" }
facet-core = { version = "0.4.0", path = "facet-core" }
facet-samplelibc = { version = "0.1.11", path = "facet-samplelibc" }
unsynn = "0.0.25"
