[workspace]
# members = ["shapely", "shapely-codegen", "shapely-trait", "shapely-derive", "shapely-json", "shapely-msgpack", "shapely-pretty", "shapely-urlencoded", "shapely-yaml"]
members = [
    "shapely",
    "shapely-codegen",
    "shapely-trait",
    "shapely-derive",
    "shapely-json",
    "shapely-opaque",
    "shapely-peek",
    "shapely-poke",
    "shapely-spez",
    "shapely-types", "shapely-samplelibc",
]
resolver = "3"

[workspace.package]
version = "3.1.0"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/shapely"
homepage = "https://github.com/bearcove/shapely"
documentation = "https://docs.rs/shapely"
description = "One trait for reflection, serialization, deserialization"
keywords = [
    "serialization",
    "deserialization",
    "reflection",
    "schema",
    "validation",
]
categories = ["encoding", "parsing", "development-tools", "data-structures"]

[workspace.dependencies]
shapely-trait = { version = "3.1.0", path = "shapely-trait" }
shapely-derive = { version = "3.1.0", path = "shapely-derive" }
unsynn = "0.0.25"
