[workspace]
members = [
    "facet",
    "facet-codegen",
    "facet-derive", "facet-json",
    "facet-json-read",
    "facet-json-write",
    "facet-msgpack",
    "facet-opaque",
    "facet-peek",
    "facet-poke",
    "facet-pretty",
    "facet-samplelibc",
    "facet-spez",
    "facet-trait",
    "facet-types",
    "facet-yaml",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.86.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/facet-rs/facet"

[workspace.dependencies]
facet = { version = "0.1.2", path = "facet" }
facet-trait = { version = "0.1.2", path = "facet-trait" }
facet-derive = { version = "0.1.2", path = "facet-derive" }
facet-opaque = { version = "0.1.2", path = "facet-opaque" }
facet-peek = { version = "0.1.2", path = "facet-peek" }
facet-poke = { version = "0.1.2", path = "facet-poke" }
facet-spez = { version = "0.1.2", path = "facet-spez" }
facet-types = { version = "0.1.2", path = "facet-types" }
facet-samplelibc = { version = "0.1.1", path = "facet-samplelibc" }
unsynn = "0.0.25"
