[workspace]
members = ["shapely", "shapely-codegen", "shapely-core", "shapely-derive", "shapely-json", "shapely-msgpack", "shapely-pretty", "shapely-urlencoded", "shapely-yaml"]
resolver = "3"

[workspace.package]
version = "3.1.0"
authors = ["Amos Wenger <amos@bearcove.eu>"]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/shapely"
homepage = "https://github.com/bearcove/shapely"
documentation = "https://docs.rs/shapely"
description = "One trait for reflection, serialization, deserialization"
keywords = [
  "serialization",
  "deserialization",
  "reflection",
  "schema",
  "validation",
]
categories = ["encoding", "parsing", "development-tools", "data-structures"]

[workspace.dependencies]
shapely = { version = "3.1.0", path = "shapely" }
shapely-core = { version = "3.1.0", path = "shapely-core" }
shapely-derive = { version = "3.1.0", path = "shapely-derive" }
shapely-pretty = { version = "3.1.0", path = "shapely-pretty" }
unsynn = "0.0.25"
form_urlencoded = "1.2.1"
