[package]
name = "facet-yaml"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "YAML serialization and deserialization for Facet types"
keywords = ["yaml", "serialization", "deserialization", "reflection", "facet"]
categories = ["encoding", "parsing", "data-structures"]

[dependencies]
yaml-rust2 = "0.10.0"
facet-core = { path = "../facet-core", version = "0.5.0" }
facet-poke = { path = "../facet-poke", version = "0.6.0" }

[dev-dependencies]
facet-derive = { path = "../facet-derive", version = "0.1.17" }
