[package]
name = "facet-reflect"
version = "0.6.1"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Allows peeking (reading from) and poking (writing to) types that implement Facet"
keywords = ["reflection", "introspection", "facet", "peek", "poke"]
categories = ["development-tools", "rust-patterns"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
facet-core = { path = "../facet-core", version = "0.5.2" }

[dev-dependencies]
facet = { path = "../facet" }
facet-ansi = { path = "../facet-ansi" }
facet-pretty = { path = "../facet-pretty" }
facet-samplelibc = { path = "../facet-samplelibc" }
facet-testhelpers = { path = "../facet-testhelpers" }
log = "0.4.27"
